-- WAVE-B — Keeper Question Bank.
--
-- Background
-- ----------
-- Every time Beam (the assistant) can't fully answer a question, it tags the
-- response with a `<gap: category — description>` marker. The reader at
-- lib/ai/gaps.ts writes one row per gap into `beacon_ai_failure_log`. After a
-- couple of weeks of traffic, the log contains thousands of unresolved gaps —
-- but a typical customer's gaps cluster around 3-5 specific missing facts
-- ("we don't know their preferred channel", "we don't know who the
-- decision-maker is", etc.).
--
-- This migration adds the table that turns those clusters into outbound
-- prompts. The cron in /api/cron/keeper/generate-questions clusters gaps via
-- Voyage cosine similarity, asks Haiku to phrase one AM-readable question per
-- cluster, and writes a row here. The AM sees the question above their Beam
-- chat input ("Beam wants to learn: X") and can answer (creates a Keeper
-- fact) or dismiss.
--
-- The cluster_signature is a short stable hash of the source gap-log ids so
-- that two runs over overlapping gap-clusters don't re-generate the same
-- question while one is still pending. The partial unique index enforces this
-- only on still-pending rows — once answered/dismissed, regen is allowed if
-- the underlying gap pattern persists.
--
-- answer_fact_id ties the answered question back to the Keeper fact it
-- created (closes the loop: gap → question → fact). beacon_brain_facts.fact_id
-- is UUID (see 2026-06-04-beacon-brain-wave-1.sql) so this column is UUID too
-- — the original spec called for BIGINT but the live PK shape is UUID.
--
-- Migration-runner note: no $$ blocks, plain DDL only. The migrate.mjs
-- runner splits on `;\n` and can't parse PL/pgSQL — see CLAUDE.md.

CREATE TABLE IF NOT EXISTS keeper_questions (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Customer scope. NULL = book-level question (e.g. an AM-wide pattern).
  customer_id TEXT,
  -- Entity scope binding — used by the strip mounted on a single-customer
  -- view. Also NULL for book-level questions.
  entity_id TEXT,

  -- The AM-readable question itself. Generated by Haiku, ~60 words max.
  question_text TEXT NOT NULL,

  -- Audit trail back into the failure log. Each id in this array is a
  -- beacon_ai_failure_log.id that contributed to the cluster.
  source_failure_log_ids BIGINT[] NOT NULL,

  -- Short stable hash of the cluster's source ids. Gates regeneration of
  -- the same question while a pending copy still exists.
  cluster_signature TEXT NOT NULL,

  -- Matches lib/ai/gaps.ts GapCategory.
  category TEXT NOT NULL CHECK (category IN (
    'data_missing', 'tool_insufficient', 'out_of_scope', 'assumption_unclear'
  )),

  -- pending = awaiting AM. answered/dismissed are terminal.
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending', 'answered', 'dismissed'
  )),

  -- Answered audit.
  answered_at TIMESTAMPTZ,
  answered_by TEXT,
  -- Soft FK to beacon_brain_facts.fact_id (UUID). ON DELETE SET NULL so a
  -- Keeper hard-delete doesn't cascade away the answered question's audit
  -- row — we want to remember that the AM answered, even if the fact later
  -- gets retired.
  answer_fact_id UUID REFERENCES beacon_brain_facts(fact_id) ON DELETE SET NULL,

  -- Dismissed audit.
  dismissed_at TIMESTAMPTZ,
  dismissed_by TEXT
);

-- AM strip queries: "give me pending questions for this customer, newest first".
CREATE INDEX IF NOT EXISTS keeper_questions_customer_pending_idx
  ON keeper_questions (customer_id, created_at DESC)
  WHERE status = 'pending';

-- General time-ordered scans (admin / digest views).
CREATE INDEX IF NOT EXISTS keeper_questions_created_at_idx
  ON keeper_questions (created_at DESC);

-- Partial unique on signature for pending rows only — prevents regen of the
-- same active question, but lets a new (answered) version land later if the
-- gap pattern persists.
CREATE UNIQUE INDEX IF NOT EXISTS keeper_questions_pending_signature_uniq
  ON keeper_questions (cluster_signature)
  WHERE status = 'pending';
