/**
 * Negative Keyword Beacon — Postgres repo layer. Phase NK-2.7.
 *
 * All reads/writes against `beacon_negative_keyword_alerts`. The cron
 * writes via `upsertAlert` (idempotent on the unique dedup key); the
 * dashboard reads via `listForAm` / `listForManager`; the create-ticket
 * route updates ticket_* fields via `markTicketed`; the dismiss action
 * stamps dismissed_* via `markDismissed`.
 *
 * Soft-fail contract:
 *   - `getSql()` returns null when POSTGRES_URL is unset (local dev
 *     without env). All public functions in this file treat that as a
 *     no-op + return safe defaults so the surface doesn't crash.
 *   - Other Postgres errors propagate to the caller — they're real bugs.
 */

import "server-only";
import { getSql } from "@/lib/customer/postgres";
import type {
  AlertItem,
  AlertSource,
  RiskCategory,
  Classifier,
} from "./types";

/** Input shape for a fresh alert write — id/timestamps generated by DB. */
export interface UpsertAlertInput {
  entity_id: string;
  customer_id: string | null;
  business_name: string;
  am_name: string | null;
  owning_am_email: string;

  source: AlertSource;
  subject: string | null;
  message_body: string | null;
  message_date: string; // YYYY-MM-DD
  message_time: string | null; // HH:MM:SS
  sender: string | null;

  risk_category: RiskCategory;
  analysis: string;
  classifier: Classifier;

  dedup_key: string;
}

/**
 * Idempotent UPSERT keyed on (source, entity_id, dedup_key).
 * On conflict: bump last_seen_at + refresh owning_am_email + am_name
 * (AM reassignments propagate). Returns the (possibly new) row id.
 */
export async function upsertAlert(
  row: UpsertAlertInput,
): Promise<{ id: string; inserted: boolean } | null> {
  const sql = getSql();
  if (!sql) return null;

  const result = (await sql`
    INSERT INTO beacon_negative_keyword_alerts (
      entity_id, customer_id, business_name, am_name, owning_am_email,
      source, subject, message_body, message_date, message_time, sender,
      risk_category, analysis, classifier, dedup_key
    ) VALUES (
      ${row.entity_id},
      ${row.customer_id},
      ${row.business_name},
      ${row.am_name},
      ${row.owning_am_email},
      ${row.source},
      ${row.subject},
      ${row.message_body},
      ${row.message_date},
      ${row.message_time},
      ${row.sender},
      ${row.risk_category},
      ${row.analysis},
      ${row.classifier},
      ${row.dedup_key}
    )
    ON CONFLICT (source, entity_id, dedup_key) DO UPDATE SET
      last_seen_at = now(),
      owning_am_email = EXCLUDED.owning_am_email,
      am_name = EXCLUDED.am_name,
      business_name = EXCLUDED.business_name
    RETURNING id, (xmax = 0) AS inserted
  `) as Array<{ id: string; inserted: boolean }>;

  if (!result.length) return null;
  return { id: result[0].id, inserted: result[0].inserted };
}

/** Common filter shape for list reads. */
export interface ListAlertsFilter {
  /** Show ALL (default), open-only (no ticket, not dismissed), or with-ticket. */
  status?: "all" | "open" | "ticketed" | "dismissed";
  /** ISO date YYYY-MM-DD. Defaults to (today - 14d). */
  since?: string;
  /** Optional category filter. */
  category?: RiskCategory;
  /** Optional source filter. */
  source?: AlertSource;
  /** Pagination cap. Default 500, max 2000. */
  limit?: number;
}

function clampLimit(n: number | undefined): number {
  if (!n || Number.isNaN(n)) return 500;
  return Math.max(1, Math.min(2000, Math.floor(n)));
}

function defaultSince(): string {
  const d = new Date();
  d.setDate(d.getDate() - 14);
  return d.toISOString().slice(0, 10);
}

/**
 * AM-scoped read. Filters at the DB level on owning_am_email = email.
 * Used by /api/alerts when session role is "am".
 *
 * Uses the Beacon-standard dynamic-filter pattern `(${param}::type IS NULL
 * OR col = ${param})` — works on the neon tagged-template driver without
 * needing parameterized clause composition or string interpolation.
 */
export async function listForAm(
  amEmail: string,
  filter: ListAlertsFilter = {},
): Promise<AlertItem[]> {
  const sql = getSql();
  if (!sql) return [];

  const since = filter.since || defaultSince();
  const limit = clampLimit(filter.limit);
  const status = filter.status || "all";
  const category = filter.category ?? null;
  const source = filter.source ?? null;

  // Status maps to boolean flags so the same WHERE works for all four.
  const wantOpen = status === "open";
  const wantTicketed = status === "ticketed";
  const wantDismissed = status === "dismissed";

  const rows = (await sql`
    SELECT *
    FROM beacon_negative_keyword_alerts
    WHERE owning_am_email = ${amEmail}
      AND message_date >= ${since}
      AND (NOT ${wantOpen} OR (ticket_id IS NULL AND dismissed_at IS NULL))
      AND (NOT ${wantTicketed} OR ticket_id IS NOT NULL)
      AND (NOT ${wantDismissed} OR dismissed_at IS NOT NULL)
      AND (${category}::text IS NULL OR risk_category = ${category})
      AND (${source}::text IS NULL OR source = ${source})
    ORDER BY message_date DESC, message_time DESC NULLS LAST
    LIMIT ${limit}
  `) as AlertItem[];

  return rows;
}

/** Manager/admin-scoped read — same shape but no AM filter. */
export async function listForManager(
  filter: ListAlertsFilter = {},
): Promise<AlertItem[]> {
  const sql = getSql();
  if (!sql) return [];

  const since = filter.since || defaultSince();
  const limit = clampLimit(filter.limit);
  const status = filter.status || "all";
  const category = filter.category ?? null;
  const source = filter.source ?? null;

  const wantOpen = status === "open";
  const wantTicketed = status === "ticketed";
  const wantDismissed = status === "dismissed";

  const rows = (await sql`
    SELECT *
    FROM beacon_negative_keyword_alerts
    WHERE message_date >= ${since}
      AND (NOT ${wantOpen} OR (ticket_id IS NULL AND dismissed_at IS NULL))
      AND (NOT ${wantTicketed} OR ticket_id IS NOT NULL)
      AND (NOT ${wantDismissed} OR dismissed_at IS NOT NULL)
      AND (${category}::text IS NULL OR risk_category = ${category})
      AND (${source}::text IS NULL OR source = ${source})
    ORDER BY message_date DESC, message_time DESC NULLS LAST
    LIMIT ${limit}
  `) as AlertItem[];

  return rows;
}

/** Single-row read by id — for the ticket-creation flow. */
export async function getAlertById(id: string): Promise<AlertItem | null> {
  const sql = getSql();
  if (!sql) return null;
  const rows = (await sql`
    SELECT * FROM beacon_negative_keyword_alerts WHERE id = ${id} LIMIT 1
  `) as AlertItem[];
  return rows[0] ?? null;
}

/**
 * Stamp ticket fields after a successful Linear creation. Idempotent —
 * re-running with the same payload is a no-op.
 */
export async function markTicketed(
  id: string,
  ticket: {
    ticket_id: string;
    ticket_identifier: string;
    ticket_url: string;
    created_by_email: string;
  },
): Promise<void> {
  const sql = getSql();
  if (!sql) return;
  await sql`
    UPDATE beacon_negative_keyword_alerts
    SET ticket_id = ${ticket.ticket_id},
        ticket_identifier = ${ticket.ticket_identifier},
        ticket_url = ${ticket.ticket_url},
        ticket_created_at = now(),
        ticket_created_by_email = ${ticket.created_by_email}
    WHERE id = ${id}
  `;
}

/** Stamp dismissal fields when an AM clicks "not a signal". */
export async function markDismissed(
  id: string,
  dismissedByEmail: string,
  reason: string | null,
): Promise<void> {
  const sql = getSql();
  if (!sql) return;
  await sql`
    UPDATE beacon_negative_keyword_alerts
    SET dismissed_at = now(),
        dismissed_by_email = ${dismissedByEmail},
        dismissed_reason = ${reason}
    WHERE id = ${id}
  `;
}

/**
 * "Has this entity got an open ticket already?" — used by the cron to
 * skip re-creating duplicate alerts when one is already in Linear, and
 * by `linear.ts` as a Beacon-side dedup pre-check before hitting Linear.
 */
export async function hasOpenTicketForEntity(
  entityId: string,
): Promise<boolean> {
  const sql = getSql();
  if (!sql) return false;
  const rows = (await sql`
    SELECT 1
    FROM beacon_negative_keyword_alerts
    WHERE entity_id = ${entityId}
      AND ticket_id IS NOT NULL
    LIMIT 1
  `) as Array<{ "?column?": number }>;
  return rows.length > 0;
}
